In [2]:
import numpy as np

## DataTypes & Attribute

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3.4],
              [4,5,6.5]])

In [7]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a3.shape

(3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 2)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [14]:
# Create a DataFram from Numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

,0,1,2
0,1.0,2.0,3.4
1,4.0,5.0,6.5


# 2. Creating Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
zeros = np.zeros((3,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
len(zeros)

3

In [ ]:
zeros = np.arange(0, 10, 3)

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,3)

In [27]:
range_array

array([0, 3, 6, 9])

In [28]:
range_array = np.arange(0,10,0.1)

In [29]:
range_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [30]:
random_array = np.random.randint(0,10,size=(3,5))

In [31]:
random_array

array([[2, 5, 6, 0, 8],
       [2, 8, 4, 5, 6],
       [5, 0, 9, 6, 4]])

In [32]:
random_array = np.random.randint(0,10,size=(3))

In [33]:
random_array

array([2, 1, 0])

In [34]:
random_array = np.random.randint(0,10,size=2)

In [35]:
random_array

array([7, 2])

In [39]:
np.random.random((1,100))

array([[0.29902737, 0.28394412, 0.68689008, 0.90425374, 0.67507875,
        0.8129484 , 0.92471751, 0.09318864, 0.88444783, 0.40747873,
        0.73659112, 0.39555695, 0.90608597, 0.53873263, 0.57706747,
        0.57596764, 0.76886397, 0.98134581, 0.06678798, 0.54038243,
        0.88281163, 0.09843386, 0.2387926 , 0.37418787, 0.17710942,
        0.40627059, 0.10058274, 0.30117296, 0.75361099, 0.07507744,
        0.58063274, 0.67344969, 0.10729705, 0.33146661, 0.27861314,
        0.43355897, 0.11894827, 0.23134715, 0.79370811, 0.80098954,
        0.91394529, 0.56092399, 0.45213584, 0.91560983, 0.21210947,
        0.61925247, 0.10616162, 0.71899347, 0.38010596, 0.34077539,
        0.8249585 , 0.5370471 , 0.36888158, 0.8699467 , 0.85723947,
        0.67624783, 0.48664988, 0.31531625, 0.62602042, 0.09279171,
        0.70651773, 0.96529782, 0.76842939, 0.82523361, 0.6571343 ,
        0.44406935, 0.05925211, 0.54149846, 0.90098953, 0.98488653,
        0.62206509, 0.31718736, 0.06106671, 0.58