In [2]:
import numpy as np

## DataTypes & Attribute

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3.4],
              [4,5,6.5]])

In [7]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a3.shape

(3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 2)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [14]:
# Create a DataFram from Numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [15]:
df

,0,1,2
0,1.0,2.0,3.4
1,4.0,5.0,6.5


# 2. Creating Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
zeros = np.zeros((3,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
len(zeros)

3

In [ ]:
zeros = np.arange(0, 10, 3)

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,3)

In [27]:
range_array

array([0, 3, 6, 9])

In [28]:
range_array = np.arange(0,10,0.1)

In [29]:
range_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [30]:
random_array = np.random.randint(0,10,size=(3,5))

In [31]:
random_array

array([[2, 5, 6, 0, 8],
       [2, 8, 4, 5, 6],
       [5, 0, 9, 6, 4]])

In [32]:
random_array = np.random.randint(0,10,size=(3))

In [33]:
random_array

array([2, 1, 0])

In [34]:
random_array = np.random.randint(0,10,size=2)

In [35]:
random_array

array([7, 2])

In [39]:
np.random.random((1,100))

array([[0.29902737, 0.28394412, 0.68689008, 0.90425374, 0.67507875,
        0.8129484 , 0.92471751, 0.09318864, 0.88444783, 0.40747873,
        0.73659112, 0.39555695, 0.90608597, 0.53873263, 0.57706747,
        0.57596764, 0.76886397, 0.98134581, 0.06678798, 0.54038243,
        0.88281163, 0.09843386, 0.2387926 , 0.37418787, 0.17710942,
        0.40627059, 0.10058274, 0.30117296, 0.75361099, 0.07507744,
        0.58063274, 0.67344969, 0.10729705, 0.33146661, 0.27861314,
        0.43355897, 0.11894827, 0.23134715, 0.79370811, 0.80098954,
        0.91394529, 0.56092399, 0.45213584, 0.91560983, 0.21210947,
        0.61925247, 0.10616162, 0.71899347, 0.38010596, 0.34077539,
        0.8249585 , 0.5370471 , 0.36888158, 0.8699467 , 0.85723947,
        0.67624783, 0.48664988, 0.31531625, 0.62602042, 0.09279171,
        0.70651773, 0.96529782, 0.76842939, 0.82523361, 0.6571343 ,
        0.44406935, 0.05925211, 0.54149846, 0.90098953, 0.98488653,
        0.62206509, 0.31718736, 0.06106671, 0.58

In [52]:
np.random.seed(0)
random_array_2 = np.random.randint(10, size=(10,10))
random_array_2

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [55]:
random_array_2.shape

(10, 10)

# 3. Viewing Arrays and Matrices

In [56]:
np.unique(random_array_2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a1

array([1, 2, 3])

In [58]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [59]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a1[0]

np.int64(1)

In [61]:
a3[0]

array([1, 2, 3])

In [62]:
a3[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a3[:2, :2]

array([[1, 2],
       [4, 5]])

In [65]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]],

        [[9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8],
         [8, 8, 2, 3, 2]],

        [[0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8],
         [0, 8, 5, 9, 0]]],


       [[[9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9],
         [2, 8, 6, 6, 9]],

        [[1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4],
         [6, 5, 8, 2, 3]],

        [[9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2],
         [3, 9, 7, 7, 5]]]])

In [66]:
a4.shape

(2, 3, 4, 5)

In [68]:
a4[:, :, :, :2]

array([[[[0, 3],
         [5, 9],
         [2, 9],
         [2, 3]],

        [[9, 1],
         [2, 3],
         [0, 6],
         [8, 8]],

        [[0, 8],
         [2, 8],
         [4, 3],
         [0, 8]]],


       [[[9, 6],
         [8, 0],
         [5, 7],
         [2, 8]],

        [[1, 6],
         [2, 3],
         [5, 7],
         [6, 5]],

        [[9, 7],
         [5, 3],
         [9, 9],
         [3, 9]]]])

# 4. Manipulating and comparing arrays

## Arithmatic

In [70]:
a1

array([1, 2, 3])

In [71]:
a1 * 2

array([2, 4, 6])

In [79]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [80]:
a1 + ones

array([2., 3., 4.])

In [81]:
a1 * ones

array([1., 2., 3.])

In [82]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [83]:
a1

array([1, 2, 3])

In [84]:
a2 = np.array([3,4,5.5])

In [85]:
a1 / a1

array([1., 1., 1.])

In [86]:
a1 / a2

array([0.33333333, 0.5       , 0.54545455])

In [87]:
a1 // a2

array([0., 0., 0.])

In [88]:
a2 ** a1

array([  3.   ,  16.   , 166.375])

In [89]:
np.square(a2)

array([ 9.  , 16.  , 30.25])

In [90]:
np.log(a2)

array([1.09861229, 1.38629436, 1.70474809])

## Aggregation

Aggregation = performing the same operation on a number of things

In [91]:
listy = [12,3,45,6]

In [92]:
type(listy)

list

In [93]:
sum(listy)

66

In [94]:
type(a1)

numpy.ndarray

In [95]:
sum(a1)

np.int64(6)

In [96]:
np.sum(a1)

np.int64(6)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`)

In [97]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [98]:
massive_array[:100]

array([7.49999249e-01, 3.39403819e-01, 4.89548937e-01, 3.38985117e-01,
       1.79490261e-01, 1.70986599e-01, 4.63450977e-01, 8.74572958e-01,
       9.44119751e-01, 6.08252866e-01, 5.96655406e-01, 7.83644245e-01,
       5.00026298e-01, 5.03700568e-02, 6.99098075e-01, 9.92396399e-01,
       2.67262538e-01, 6.79090616e-01, 8.64281443e-01, 7.50844246e-01,
       9.64489768e-01, 5.54242435e-01, 2.12390499e-01, 2.22443224e-01,
       2.18749374e-01, 5.69573535e-01, 4.52109035e-01, 9.70236683e-01,
       6.80544691e-01, 8.52955659e-02, 5.64183327e-02, 4.87837704e-01,
       8.81004562e-01, 9.76404387e-01, 6.17657916e-01, 5.42498775e-01,
       8.54613580e-01, 7.43834545e-01, 4.78596326e-01, 6.77081574e-01,
       6.07045061e-01, 7.14696936e-01, 4.69497183e-01, 4.56014623e-01,
       9.06418087e-01, 1.37220420e-01, 2.29219323e-01, 8.81585399e-01,
       9.04424976e-01, 6.45784599e-01, 3.24682972e-01, 5.19711194e-01,
       5.53568650e-05, 3.11860221e-01, 4.25451538e-01, 8.85337660e-01,
      

In [99]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

2.95 ms ± 130 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.2 μs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [100]:
2950 / 12

245.83333333333334

In [101]:
a2

array([3. , 4. , 5.5])

In [102]:
np.mean(a2)

np.float64(4.166666666666667)

In [103]:
np.max(a1)

np.int64(3)

In [109]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a1)

np.float64(0.816496580927726)

In [107]:
# Variance = measure of avarage degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers

np.var(a1)

np.float64(0.6666666666666666)

In [108]:
np.sqrt(np.var(a1))

np.float64(0.816496580927726)