In [2]:
import numpy as np

## DataTypes & Attribute

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2,3.4],
              [4,5,6.5]])

In [11]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [12]:
a2.shape

(2, 3)

In [13]:
a3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a3.shape

(3, 3)

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 2)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [18]:
# Create a DataFram from Numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [19]:
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  6.5